define({
  root: ({
    _widgetLabel: "Attribute Table",
    _featureAction_ShowRelatedRecords: "Show Related Records",
    _featureAction_ViewInTable: "View in Attribute Table",
    ok: "OK",
    cancel: "Cancel",
    unsupportQueryWarning: "The layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",
    exportMessage: "Export data to CSV file?",
    exportFiles: "Export to CSV",
    exportSelected: "Export Selected to CSV",
    exportAll: "Export All to CSV",
    options: "Options",
    zoomto: "Zoom to",
    highlight: "Highlight Graphics",
    selectAll: "Select Records in All Pages",
    selectPage: "Select Records in Current Page",
    clearSelection: "Clear Selection",
    filter: "Filter",
    setFilterTip: "Please set filter correctly.",
    noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source.",
    filterByExtent: "Filter by Map Extent",
    showSelectedRecords: "Show Selected Records",
    showAllRecords: "Show All Records",
    showRelatedRecords: "Show Related Records",
    noRelatedRecords: "No related records found",
    refresh: "Refresh",
    features: "features",
    records: "records",
    selected: "selected",
    transparent: "Transparent Mode",
    indicate: "Locate Selection",
    columns: "Show/Hide Columns",
    selectionSymbol: "Selection Symbol",
    closeMessage: "Hide Table (expand it again from the bottom)",
    dataNotAvailable: "Data not available!<br>Click [Refresh] button to try again.",
    openTableTip: "Open Attribute Table",
    closeTableTip: "Hide Attribute Table",
    sortAsc: "Sort Ascending",
    sortDes: "Sort Descending",
    statistics: "Statistics"
  })
});